services:
  redis:
    build: ./reqs/redis
    image: redis
    container_name: inception-redis
    restart: unless-stopped
    networks:
      - inception

  mariadb:
    build: ./reqs/mariadb
    image: mariadb
    container_name: inception-mariadb
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    secrets:
      - db_root_password
      - db_password

  wordpress:
    build: ./reqs/wordpress
    image: wordpress
    container_name: inception-wordpress
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password

  ftp:
    build: ./reqs/ftp
    image: ftp
    container_name: inception-ftp
    restart: unless-stopped
    stop_signal: SIGKILL
    volumes:
      - wordpress_data:/var/www/wordpress
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    depends_on:
      - wordpress
    secrets:
      - ftp_password

  nginx:
    build: ./reqs/nginx
    image: nginx
    container_name: inception-nginx
    # restart always if not manually stopped
    restart: unless-stopped
    # necessary for envsubst
    env_file: ./.env
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress

  adminer:
    build: ./reqs/adminer
    image: adminer
    container_name: inception-adminer
    restart: unless-stopped
    # php needs SIGINT to stop gracefully, not SIGTERM
    stop_signal: SIGINT
    stop_grace_period: 3s
    networks:
      - inception
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

  static:
    build: ./reqs/static
    image: static
    container_name: inception-static
    restart: unless-stopped
    stop_signal: SIGINT
    ports:
      - "4242:4242"

  portainer:
    build: ./reqs/portainer
    image: portainer
    container_name: inception-portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    secrets:
      - portainer_password

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    name: 'wordpress_data'
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUMES_PATH}/wordpress

  db_data:
    name: 'db_data'
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUMES_PATH}/mariadb

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
  portainer_password:
    file: ../secrets/portainer_password.txt
