listen=YES

anonymous_enable=NO
local_enable=YES
write_enable=YES

local_root=/var/www/wordpress
chroot_local_user=YES
allow_writeable_chroot=YES

pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110

# disable seccomp sandbox to avoid docker related issues 
seccomp_sandbox=NO
background=NO
